[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
]
exceptions = []
deny = [
    { triple = "i686-unknown-linux-gnu" },
    { triple = "armv7-unknown-linux-gnueabihf" },
]
copyleft = "deny"

[[bans]]
name = "ddot"
multiple = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
